#!/bin/bash
# mcar — Interactive setup script
# Creates .env, tests DB connection, generates admin hash.
# Run on the server from the project root:
#   bash setup.sh

set -e

# Colors
G='\033[0;32m'; R='\033[0;31m'; Y='\033[1;33m'; B='\033[0;34m'; N='\033[0m'

echo -e "${B}╔═══════════════════════════════════════════════╗${N}"
echo -e "${B}║        mcar — Interactive Setup Wizard        ║${N}"
echo -e "${B}╚═══════════════════════════════════════════════╝${N}"
echo ""

# Confirm we're in the right directory
if [ ! -f "index.php" ] || [ ! -d "includes" ]; then
    echo -e "${R}✗ Error: Run this script from the project root (where index.php lives).${N}"
    echo -e "  Try: ${Y}cd ~/applications/*/public_html && bash setup.sh${N}"
    exit 1
fi

echo -e "${G}✓ In project directory: $(pwd)${N}"
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo -e "${Y}⚠  .env already exists.${N}"
    read -p "Overwrite? (y/N): " overwrite
    if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
        echo "Aborted."; exit 0
    fi
    cp .env .env.backup.$(date +%s)
    echo -e "${G}✓ Old .env backed up to .env.backup.*${N}"
fi

# ---------- DB Credentials ----------
echo ""
echo -e "${B}━━━ 1/4: Database credentials ━━━${N}"
echo "(Find these in Cloudways → Application → Access Details → Database)"
read -p "DB Name     [rdcbvmjwbe]: " DB_NAME
DB_NAME=${DB_NAME:-rdcbvmjwbe}
read -p "DB User     [$DB_NAME]:   " DB_USER
DB_USER=${DB_USER:-$DB_NAME}
read -sp "DB Password:              " DB_PASS
echo ""

# ---------- Admin ----------
echo ""
echo -e "${B}━━━ 2/4: Admin panel credentials ━━━${N}"
read -p "Admin username [saar]: " ADMIN_USER
ADMIN_USER=${ADMIN_USER:-saar}
read -sp "Admin password (min 8 chars, this is for /admin/login): " ADMIN_PASS
echo ""
read -sp "Confirm admin password:                                 " ADMIN_PASS2
echo ""
if [ "$ADMIN_PASS" != "$ADMIN_PASS2" ]; then
    echo -e "${R}✗ Passwords don't match. Abort.${N}"; exit 1
fi
if [ ${#ADMIN_PASS} -lt 8 ]; then
    echo -e "${R}✗ Password too short (min 8). Abort.${N}"; exit 1
fi

# Generate bcrypt hash
ADMIN_HASH=$(php -r "echo password_hash('$ADMIN_PASS', PASSWORD_BCRYPT);")
if [ -z "$ADMIN_HASH" ]; then
    echo -e "${R}✗ password_hash failed. Is PHP available?${N}"; exit 1
fi
echo -e "${G}✓ bcrypt hash generated${N}"

# ---------- Email ----------
echo ""
echo -e "${B}━━━ 3/4: Email (where leads arrive) ━━━${N}"
read -p "Your email address to receive leads [vip@mcar.co.il]: " MAIL_TO
MAIL_TO=${MAIL_TO:-vip@mcar.co.il}
read -p "'From' address for outgoing emails [noreply@mcar.co.il]: " MAIL_FROM
MAIL_FROM=${MAIL_FROM:-noreply@mcar.co.il}

# ---------- App ----------
echo ""
echo -e "${B}━━━ 4/4: Environment ━━━${N}"
read -p "APP_URL (e.g. https://mcar.co.il): " APP_URL
APP_URL=${APP_URL:-}

# ---------- Write .env ----------
cat > .env << EOF
# mcar — Environment Config
# Generated by setup.sh at $(date)

# Database
DB_HOST=localhost
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASS=$DB_PASS
DB_CHARSET=utf8mb4

# Email
MAIL_TO=$MAIL_TO
MAIL_FROM=$MAIL_FROM
MAIL_FROM_NAME=mcar
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_SECURE=tls

# reCAPTCHA v3 (add later via https://www.google.com/recaptcha/admin)
RECAPTCHA_SITE_KEY=
RECAPTCHA_SECRET_KEY=
RECAPTCHA_MIN_SCORE=0.5

# Admin
ADMIN_USER=$ADMIN_USER
ADMIN_PASS_HASH=$ADMIN_HASH

# App
APP_ENV=production
APP_DEBUG=false
APP_URL=$APP_URL
EOF

chmod 600 .env
echo -e "${G}✓ .env written (600 permissions)${N}"

# ---------- Tests ----------
echo ""
echo -e "${B}━━━ Running tests ━━━${N}"

# Test 1: DB connection
TEST_DB=$(php -r "require 'includes/db.php'; echo db() ? 'OK' : 'FAIL';" 2>&1)
if [ "$TEST_DB" = "OK" ]; then
    echo -e "${G}✓ Database connection: OK${N}"
else
    echo -e "${R}✗ Database connection: FAIL${N}"
    echo "  ($TEST_DB)"
    echo "  Check DB_PASS in .env. You may need to reset the Cloudways DB password."
fi

# Test 2: Tables exist
TEST_TABLES=$(php -r "require 'includes/db.php'; \$c=db(); if(!\$c){echo 0;exit;} echo \$c->query('SELECT COUNT(*) FROM cars')->fetchColumn();" 2>&1)
if [ "$TEST_TABLES" -ge 1 ] 2>/dev/null; then
    echo -e "${G}✓ Tables + seed data: OK ($TEST_TABLES cars)${N}"
else
    echo -e "${Y}⚠ Tables not yet imported or seed empty.${N}"
    echo "  Next: Import migrations/001_schema.sql, 002_seed.sql, 003_cms_schema.sql via phpMyAdmin"
fi

# Test 3: uploads dir
if [ -d "uploads" ]; then
    chmod 755 uploads/
    echo -e "${G}✓ uploads/ directory: OK${N}"
else
    mkdir -p uploads/
    chmod 755 uploads/
    echo -e "${G}✓ uploads/ directory: created${N}"
fi

# Test 4: admin login page
ADMIN_URL="${APP_URL%/}/admin/login.php"
echo ""
echo -e "${B}━━━ Done! ━━━${N}"
echo ""
echo -e "  ${G}Admin URL:${N}      $ADMIN_URL"
echo -e "  ${G}Username:${N}       $ADMIN_USER"
echo -e "  ${G}Password:${N}       (the one you just entered)"
echo ""
echo -e "  ${Y}Next: import migration files via phpMyAdmin${N}"
echo -e "    → Launch Database Manager"
echo -e "    → Import migrations/001_schema.sql"
echo -e "    → Import migrations/002_seed.sql"
echo -e "    → Import migrations/003_cms_schema.sql"
echo ""
echo -e "  ${Y}Security:${N}"
echo -e "    ✓ .env is git-ignored and chmod 600"
echo -e "    ⚠  Rotate your SSH password now: Cloudways → Server → Master Credentials"
echo ""
